/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package taxUnit;

import java.awt.CardLayout;
import java.awt.Component;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.*;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;

/**
 *
 * @author dheer
 */
public class TaxEmployeePage extends javax.swing.JPanel {

    /**
     * Creates new form TaxEmployeePage
     */
    JPanel rightLayout;
    String id;
     String from;
    String to;
    String host;
    String sub;
    String content;
    public TaxEmployeePage(JPanel rightLayout,String id) {
        this.rightLayout=rightLayout;
        this.id=id;
        initComponents();
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jButton3.setBackground(new java.awt.Color(255, 0, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("LOGOUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(1760, 10, 96, 38);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "USER ID", "PAYER_NAME", "TAX_ID", "SIN", "ACCOUN  NUMBER", "START_DURATION", "END_DURATION", "ANNUAL_INCOME", "TAXES_PAID", "STATUS", "REFERRED"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 55, 1920, 160);

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setText("APPROVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(0, 220, 106, 38);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2975879.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1980, 1080);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        rightLayout.remove(this);
        Component [] componentArray = rightLayout.getComponents();
        Component c = componentArray[componentArray.length-1];
        CardLayout layout = (CardLayout) rightLayout.getLayout();
        layout.previous(rightLayout);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    public void table(){
        DefaultTableModel tbl = (DefaultTableModel)table.getModel();
        tbl.setRowCount(0);
              try{
      Connection cn= db_connection.DatabaseConnector.getConnection();
      
       
     
        Statement st= cn.createStatement();
      String sql = "select * from TAX_EMPLOYEE";
      ResultSet ps= st.executeQuery(sql);
      

      
          while(ps.next()){
           
           Object[] row = new Object[20];
          row[0]=ps.getString("USERID");
          row[1]=ps.getString("CLAIM_NAME");
          row[2]=ps.getString("TAX_ID");
          row[3]=ps.getString("SIN");
          row[4]=ps.getString("ACCOUNT_NUMBER");
          row[5]=ps.getString("START_DURATION");
          row[6]=ps.getString("END_DURATION");
          row[7]=ps.getString("ANNUAL_INCOME");
          row[8]=ps.getString("TAXES_PAID");
          row[9]=ps.getString("STATUS");
          row[10]=ps.getString("REFERRED");
          tbl.addRow(row);
         
          }
       }catch(Exception e){
          JOptionPane.showMessageDialog(this,e);
      }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selected =table.getSelectedRow();
        int count=0;
        if(selected<0){
            JOptionPane.showMessageDialog(this, "No Row has been selected");
            return;
        }
        DefaultTableModel tbl= (DefaultTableModel)table.getModel();
        String taxId="";
        String status="";
        String account="";
        String amount="";
        String actual="";
        String id1= tbl.getValueAt(selected, 2).toString();
        try{
            String s1="";
            Connection cn= db_connection.DatabaseConnector.getConnection();

            Statement st= cn.createStatement();
            String sql = "select * from TAX_EMPLOYEE";
            ResultSet ps= st.executeQuery(sql);

            while(ps.next()){
                if(ps.getString("TAX_ID").equalsIgnoreCase(id1)){
                    taxId= ps.getString("TAX_ID");
                    s1=ps.getString("STATUS");
                    status="APPROVED";
                    amount= ps.getString("TAXES_PAID");
                    account=ps.getString("ACCOUNT_NUMBER");
                }
            }
             try{
            
            Connection cn5= db_connection.DatabaseConnector.getConnection();

            Statement st8= cn5.createStatement();
            String sql8 = "select * from BANK";
            ResultSet ps8= st8.executeQuery(sql8);
            while(ps8.next()){
                if(ps8.getString("ACCOUNT_NUMBER").matches(account)){
                    actual= ps8.getString("AMOUNT");
                }
            }
            }catch(Exception e){
                            e.printStackTrace();
                        }

            if(!(s1.equalsIgnoreCase("APPROVED"))){
                
                
                int total=0;
                total= Integer.parseInt(actual)+Integer.parseInt(amount);
                
                String sql1= "UPDATE TAXES SET STATUS='APPROVED' WHERE TAX_ID='"+taxId+"'";
                PreparedStatement ps1= cn.prepareStatement(sql1);
                ps1.execute();

                String sql2= "UPDATE TAX_OFFICER SET STATUS='APPROVED' WHERE TAX_ID='"+taxId+"'";
                PreparedStatement ps2= cn.prepareStatement(sql2);
                ps2.execute();

                String sql3= "UPDATE TAX_EMPLOYEE SET STATUS='APPROVED' WHERE TAX_ID='"+taxId+"'";
                PreparedStatement ps3= cn.prepareStatement(sql3);
                ps3.execute();
                
                String sql6= "UPDATE BANK SET AMOUNT='"+total+"' WHERE ACCOUNT_NUMBER='"+account+"'";
                PreparedStatement ps6= cn.prepareStatement(sql6);
                ps6.execute();
                
                
                String sql9= "UPDATE BANK_MANAGER SET AMOUNT='"+total+"' WHERE ACCOUNT_NUMBER='"+account+"'";
                PreparedStatement ps9= cn.prepareStatement(sql9);
                ps9.execute();
                
                
                 String sql10= "UPDATE BANK_EMPLOYEE SET AMOUNT='"+total+"' WHERE ACCOUNT_NUMBER='"+account+"'";
                PreparedStatement ps10= cn.prepareStatement(sql10);
                ps10.execute();
                
                String bankName="";
                String name="";
                String email="";
                try{
                    Connection cn1= db_connection.DatabaseConnector.getConnection();

                    Statement st4= cn1.createStatement();
                    String sql4 = "SELECT * FROM USER";
                    ResultSet ps4= st4.executeQuery(sql4);

                    Statement st5= cn1.createStatement();
                    String sql5 = "SELECT * FROM TAX_EMPLOYEE";
                    ResultSet ps5= st5.executeQuery(sql5);

                   while(ps5.next()){
                            while(ps4.next()){
                                if(ps5.getString("USERID").equalsIgnoreCase(ps4.getString("ID"))){
                                    name= ps4.getString("NAME");
                                    email=  ps4.getString("EMAIL");

                                }}}
                            
                        }catch(Exception e){
                            JOptionPane.showMessageDialog(this,e);
                        }
                
                        from ="dheerajjayanth@gmail.com";
                        to=email;
                        host="localhost";
                        sub="Your "+taxId+" has Accepted";
                        content= "Hi "+name+",\n"
                        + "\n"
                        + "We have Accepted your "+taxId+" application. You are able to see your claim amount into your account. If you have any queries please contact the tax office for more information.\n"
                        + "\n"
                        + "Thanks and Regards,\n"
                        + "TAX_EMPLOYER\n"
                        + ""+id+"\n"
                        + "\n"
                        + "If you have any concerns. Please contact us by +1 4375184224 or dheerajjayanth@gmail.com";
                        Properties p= new Properties();
                        p.put("mail.smtp.auth", "true");
                        p.put("mail.smtp.starttls.enable", "true");
                        p.put("mail.smtp.ssl.trust", "smtp.gmail.com");
                        p.put("mail.smtp.host", "smtp.gmail.com");
                        p.put("mail.smtp.port", "587");

                        Session s= Session.getDefaultInstance(p, new javax.mail.Authenticator(){
                            protected PasswordAuthentication getPasswordAuthentication(){
                                return new PasswordAuthentication("dheerajjayanth@gmail.com","rtowuvazupeivdmr");
                            }
                        });
                        try{
                            MimeMessage m = new MimeMessage(s);
                            m.setFrom(from);
                            m.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
                            m.setSubject(sub);
                            m.setText(content);
                            Transport.send(m);
                        }catch(Exception e){
                            e.printStackTrace();
                        }

                        JOptionPane.showMessageDialog(this,""+taxId+" has Successfully Approved..!!");
                        table();
                    }else{
                        JOptionPane.showMessageDialog(this,""+taxId+" has Already Approved");

                    }

                }catch(Exception e){
                    JOptionPane.showMessageDialog(this,e);
                }

                // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
