/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface;

import attributes.SystemAdmin;
import attributes.UserDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dheer
 */
public class BankEmployeeLogin extends javax.swing.JPanel {

    /**
     * Creates new form UserPortal
     */

    SystemAdmin sysAdmin;
    UserDirectory userDirectory;
    JPanel pageLayout;
    public BankEmployeeLogin(JPanel pageLayout, SystemAdmin sysAdmin) {
   
        this.sysAdmin=sysAdmin;
        this.pageLayout=pageLayout;
        initComponents();
        userDirectory= sysAdmin.getUserDirectory();
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bankEmployeeLayout = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radio = new javax.swing.JRadioButton();
        txt2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 1000));
        setLayout(null);

        bankEmployeeLayout.setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EMPLOYEE LOGIN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(590, 40, 480, 40);

        radio.setBackground(new java.awt.Color(255, 255, 255));
        radio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio.setText("VIEW");
        radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioActionPerformed(evt);
            }
        });
        jPanel1.add(radio);
        radio.setBounds(1080, 140, 60, 40);
        jPanel1.add(txt2);
        txt2.setBounds(820, 140, 250, 40);

        jButton2.setBackground(new java.awt.Color(255, 0, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(940, 200, 100, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText(":");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(790, 140, 13, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("PASSWORD");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(590, 140, 200, 40);

        txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt1MouseClicked(evt);
            }
        });
        jPanel1.add(txt1);
        txt1.setBounds(820, 90, 250, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText(":");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(790, 90, 13, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("USERNAME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(590, 90, 200, 40);

        jButton3.setBackground(new java.awt.Color(0, 102, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("LOGIN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(820, 200, 100, 40);

        jButton4.setBackground(new java.awt.Color(0, 102, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(590, 200, 100, 40);

        bankEmployeeLayout.add(jPanel1, "card2");

        add(bankEmployeeLayout);
        bankEmployeeLayout.setBounds(0, 0, 1240, 740);
    }// </editor-fold>//GEN-END:initComponents

    private void txt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseClicked
     

            // TODO add your handling code here:
    }//GEN-LAST:event_txt1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioActionPerformed
            if(radio.isSelected()){
                txt2.setEchoChar((char)0);
            }else{
                txt2.setEchoChar('*');
            }


        // TODO add your handling code here:
    }//GEN-LAST:event_radioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         String userName= txt1.getText();
        String password= txt2.getText();
        
        try{
      Connection cn= db_connection.DatabaseConnector.getConnection();
      
     Statement st= cn.createStatement();
      String sql = "select * from BANK_EMPLOYEE_LOGIN";
      ResultSet ps= st.executeQuery(sql);
      String un="";
      String pass= "";
      String id="";
       while(ps.next()){
       if(String.valueOf(ps.getString("USERNAME")).matches(userName)){
           un=String.valueOf(ps.getString("USERNAME"));
           if(String.valueOf(ps.getString("PASSWORD")).matches(password)){
               pass=String.valueOf(ps.getString("PASSWORD"));
               id=String.valueOf(ps.getString("EMPLOYEEID"));
           }
       }
       }
       if(!un.matches("")){ 
                if(!pass.matches("")){
                    clear();
        BankEmployeePage directory = new BankEmployeePage(pageLayout,id);
        pageLayout.add("BankEmployeePage",directory);
        CardLayout layout = (CardLayout)pageLayout.getLayout();
        layout.next(pageLayout);  
                }
                else{
            JOptionPane.showMessageDialog(this,"Password is Invalid");
            clear();
           }
       }else{
            JOptionPane.showMessageDialog(this,"UserName doesn't exists. Please Enter valid credentials");
            clear();
       }
       
          }catch(Exception e){
          JOptionPane.showMessageDialog(this,e);
      }   


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        pageLayout.remove(this);
        Component [] componentArray = pageLayout.getComponents();
        Component c = componentArray[componentArray.length-1];
        CardLayout layout = (CardLayout) pageLayout.getLayout();
        layout.previous(pageLayout);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
    public void clear(){
        txt1.setText("");
        txt2.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bankEmployeeLayout;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radio;
    private javax.swing.JTextField txt1;
    private javax.swing.JPasswordField txt2;
    // End of variables declaration//GEN-END:variables
}
