/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface;

import attributes.UserDirectory;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dheer
 */
public class BankAccount extends javax.swing.JPanel {

    /**
     * Creates new form BankAccount
     */
 JPanel innerLayout;
    UserDirectory userDirectory;
    String id;
    public BankAccount(JPanel innerLayout, UserDirectory userDirectory, String id) {
        this.innerLayout= innerLayout;
        this.userDirectory=userDirectory;
        this.id=id;
           initComponents();
           bank();
              }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bankLayout = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txt5 = new javax.swing.JTextField();
        txt4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        bankLayout.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BANK DETAILS");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1044, 55);

        jLabel2.setText(":");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(520, 74, 4, 40);

        jLabel3.setText("BANK");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(364, 74, 150, 40);

        txt1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT" }));
        txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt1MouseReleased(evt);
            }
        });
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        jPanel2.add(txt1);
        txt1.setBounds(528, 73, 200, 40);

        jLabel4.setText("ACCOUNT NUMBER");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(364, 120, 150, 40);

        jLabel5.setText(":");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(520, 120, 4, 40);

        jLabel6.setText("ACCOUNT TYPE");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(364, 166, 150, 40);

        jLabel7.setText(":");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(520, 166, 4, 40);

        jLabel8.setText("ACCOUNT BALANCE");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(364, 212, 150, 40);

        jLabel9.setText(":");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(520, 212, 4, 40);

        txt2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(txt2);
        txt2.setBounds(530, 120, 200, 40);

        txt3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(txt3);
        txt3.setBounds(530, 166, 200, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("CREATE A NEW BANK ACCOUNT");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10);
        jLabel10.setBounds(360, 260, 229, 29);

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("DEPOSIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(736, 295, 97, 40);

        txt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt5ActionPerformed(evt);
            }
        });
        jPanel2.add(txt5);
        txt5.setBounds(530, 297, 200, 40);

        txt4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(txt4);
        txt4.setBounds(530, 212, 200, 40);

        bankLayout.add(jPanel2, "card2");

        add(bankLayout);
        bankLayout.setBounds(0, 0, 1050, 660);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

        NewBankAccount directory = new NewBankAccount(innerLayout,userDirectory,id);
        innerLayout.add("NewBankAccount",directory);
        CardLayout layout = (CardLayout)innerLayout.getLayout();
        layout.next(innerLayout);  


        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked
    public void bank(){
        String u="";
        txt1.removeAllItems();
            try{
      Connection cn= db_connection.DatabaseConnector.getConnection();
      
     Statement st= cn.createStatement();
      String sql = "SELECT * FROM BANK";
      ResultSet ps= st.executeQuery(sql);
      
      Statement st1= cn.createStatement();
      String sql1= "SELECT * FROM USER";
      ResultSet ps1= st1.executeQuery(sql1);
       while(ps1.next()){
        if(String.valueOf(ps1.getString("ID")).matches(id))  {
            while(ps.next()){
                if(id.matches(ps.getString("USERID"))){
                    if(ps.getString("STATUS").matches("APPROVED")){
                 txt1.addItem(ps.getString("BANK_NAME"));
                    }
                }
            }
           
        }}
       
      }catch(Exception e){
          JOptionPane.showMessageDialog(this,e);
      }
    }
    private void txt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseClicked



        // TODO add your handling code here:
    }//GEN-LAST:event_txt1MouseClicked
    public void clear(){
        txt1.setSelectedItem(0);
        txt2.setIcon(null);
        txt3.setIcon(null);
        txt4.setText("");
    }
    private void txt1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseReleased
         

        // TODO add your handling code here:
    }//GEN-LAST:event_txt1MouseReleased

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        
 
        try{
      Connection cn= db_connection.DatabaseConnector.getConnection(); 
      
     Statement st= cn.createStatement();
      String sql = "SELECT * FROM BANK";
      ResultSet ps= st.executeQuery(sql);
      
      
       while(ps.next()){
        if(String.valueOf(ps.getString("BANK_NAME")).matches(String.valueOf(txt1.getSelectedItem())) && ps.getString("USERID").matches(id))  {
          txt2.setText(ps.getString("ACCOUNT_NUMBER"));
          txt3.setText(ps.getString("TYPE"));
          txt4.setText(ps.getString("AMOUNT"));
        }}
      }catch(Exception e){
          JOptionPane.showMessageDialog(this,e);
      }
    

        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(txt4.getText().matches("")){
            JOptionPane.showMessageDialog(this,"Your unable to add deposit...!!");
        }else{
        
        String account= txt2.getText();
        String amount= txt4.getText();
        String deposit=txt5.getText();
        String total=String.valueOf(Integer.parseInt(amount)+Integer.parseInt(deposit));
        
        try{
            
            Connection cn= db_connection.DatabaseConnector.getConnection();
            String sql1= "UPDATE BANK SET AMOUNT='"+total+"' WHERE ACCOUNT_NUMBER='"+account+"'";
                PreparedStatement ps1= cn.prepareStatement(sql1);
                ps1.execute();
                
                 String sql2= "UPDATE BANK_MANAGER SET AMOUNT='"+total+"' WHERE ACCOUNT_NUMBER='"+account+"'";
                PreparedStatement ps2= cn.prepareStatement(sql2);
                ps2.execute();
                
                 String sql3= "UPDATE BANK_EMPLOYEE SET AMOUNT='"+total+"' WHERE ACCOUNT_NUMBER='"+account+"'";
                PreparedStatement ps3= cn.prepareStatement(sql3);
                ps3.execute();
                
                
                JOptionPane.showMessageDialog(this,""+total+" has Deposited into your  Account: "+account+"");
                
                bank();
              
            
            }catch(Exception e){
                           JOptionPane.showMessageDialog(this,e);
                        }
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bankLayout;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    private javax.swing.JTextField txt5;
    // End of variables declaration//GEN-END:variables
}
