/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface;

import attributes.SystemAdmin;
import attributes.User;
import attributes.UserDirectory;
import java.sql.*;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dheer
 */
public class UserFrame extends javax.swing.JPanel {

    /**
     * Creates new form UserFrame
     */
    JPanel rightLayout;
    SystemAdmin sysAdmin;
    UserDirectory userDirectory;
    public UserFrame(JPanel rightLayout, SystemAdmin sysAdmin) {
        this.rightLayout=rightLayout;
        this.sysAdmin=sysAdmin;
        initComponents();
        userDirectory= sysAdmin.getUserDirectory();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt6 = new javax.swing.JComboBox<>();
        txt7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt9 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt4 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt8 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt11 = new javax.swing.JTextField();
        txt10 = new javax.swing.JPasswordField();
        radio = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD USER");
        add(jLabel1);
        jLabel1.setBounds(50, 11, 480, 52);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText(":");
        add(jLabel2);
        jLabel2.setBounds(270, 81, 13, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 102));
        jLabel3.setText("NAME");
        add(jLabel3);
        jLabel3.setBounds(60, 81, 200, 40);

        txt1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txt1ComponentAdded(evt);
            }
        });
        txt1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                txt1HierarchyChanged(evt);
            }
        });
        txt1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txt1MouseMoved(evt);
            }
        });
        txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt1MouseClicked(evt);
            }
        });
        txt1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt1InputMethodTextChanged(evt);
            }
        });
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt1KeyTyped(evt);
            }
        });
        add(txt1);
        txt1.setBounds(290, 81, 250, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText(":");
        add(jLabel4);
        jLabel4.setBounds(270, 121, 13, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 102));
        jLabel5.setText("ID");
        add(jLabel5);
        jLabel5.setBounds(60, 121, 200, 40);
        add(txt2);
        txt2.setBounds(290, 121, 250, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText(":");
        add(jLabel6);
        jLabel6.setBounds(270, 171, 13, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 102));
        jLabel7.setText("AGE");
        add(jLabel7);
        jLabel7.setBounds(60, 171, 200, 40);
        add(txt3);
        txt3.setBounds(290, 171, 250, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText(":");
        add(jLabel8);
        jLabel8.setBounds(270, 263, 13, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 102));
        jLabel9.setText("SIN NUMBER");
        add(jLabel9);
        jLabel9.setBounds(60, 263, 200, 40);
        add(txt5);
        txt5.setBounds(290, 263, 250, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText(":");
        add(jLabel10);
        jLabel10.setBounds(270, 314, 13, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 102));
        jLabel11.setText("PERMIT STATUS");
        add(jLabel11);
        jLabel11.setBounds(60, 314, 200, 40);

        txt6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "STUDY PERMIT", "WORK PERMIT", "PR", "VISITOR PERMIT" }));
        add(txt6);
        txt6.setBounds(290, 314, 250, 40);
        add(txt7);
        txt7.setBounds(290, 364, 250, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText(":");
        add(jLabel12);
        jLabel12.setBounds(270, 364, 13, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 102));
        jLabel13.setText("PERMIT NUMBER");
        add(jLabel13);
        jLabel13.setBounds(60, 364, 200, 40);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(58, 604, 100, 40);

        jButton3.setBackground(new java.awt.Color(255, 0, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(402, 604, 100, 40);

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(296, 604, 100, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 102));
        jLabel16.setText("USERNAME");
        add(jLabel16);
        jLabel16.setBounds(60, 507, 200, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText(":");
        add(jLabel17);
        jLabel17.setBounds(270, 507, 13, 40);
        add(txt9);
        txt9.setBounds(290, 507, 250, 40);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText(":");
        add(jLabel20);
        jLabel20.setBounds(268, 556, 13, 40);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 102));
        jLabel19.setText("PASSWORD");
        add(jLabel19);
        jLabel19.setBounds(58, 557, 200, 40);

        txt4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "CANADA", "USA" }));
        add(txt4);
        txt4.setBounds(290, 217, 250, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText(":");
        add(jLabel14);
        jLabel14.setBounds(270, 217, 13, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 102));
        jLabel15.setText("COUNTRY");
        add(jLabel15);
        jLabel15.setBounds(60, 217, 200, 40);
        add(txt8);
        txt8.setBounds(290, 415, 250, 40);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText(":");
        add(jLabel18);
        jLabel18.setBounds(270, 415, 13, 40);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 102));
        jLabel21.setText("PHONENUMBER");
        add(jLabel21);
        jLabel21.setBounds(60, 415, 200, 40);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 102));
        jLabel22.setText("EMAIL ID");
        add(jLabel22);
        jLabel22.setBounds(60, 461, 200, 40);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText(":");
        add(jLabel23);
        jLabel23.setBounds(270, 461, 13, 40);
        add(txt11);
        txt11.setBounds(290, 461, 250, 40);
        add(txt10);
        txt10.setBounds(290, 560, 250, 40);

        radio.setBackground(new java.awt.Color(255, 255, 255));
        radio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio.setText("VIEW");
        radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioActionPerformed(evt);
            }
        });
        add(radio);
        radio.setBounds(550, 560, 60, 40);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 51, 51));
        jLabel24.setText("Apply for new SIN...!!!");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        add(jLabel24);
        jLabel24.setBounds(546, 274, 176, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            rightLayout.remove(this);
        Component [] componentArray = rightLayout.getComponents();
        Component c = componentArray[componentArray.length-1];
        
        CardLayout layout = (CardLayout) rightLayout.getLayout();
        layout.previous(rightLayout);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clear();    
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseClicked
       
        int z=0;
        String userId1 =null;
        String y=null;
        try{
      Connection cn= db_connection.DatabaseConnector.getConnection();
      
     Statement st= cn.createStatement();
      String sql = "select * from user";
      ResultSet ps= st.executeQuery(sql);
       while(ps.next()){
                  if(String.valueOf(ps.getString("ID")).isEmpty()){
                       txt2.setText("U00"+"1"); 
                  }else{
                  userId1=String.valueOf(ps.getString("ID"));
                   z= Integer.parseInt(userId1);
                }}
         
              txt2.setText("U00"+String.valueOf(++z));

        }catch(Exception e){
          JOptionPane.showMessageDialog(this,e);
      }
 

        // TODO add your handling code here:
    }//GEN-LAST:event_txt1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String name= txt1.getText();
        String id= txt2.getText().replaceAll("U00", "");
        String age= txt3.getText();
        String country= String.valueOf(txt4.getSelectedItem());
        String sin= txt5.getText();
        String status= String.valueOf(txt6.getSelectedItem());
        String permit= txt7.getText();
        String phoneNumber= txt8.getText();
        String userName= txt9.getText();
        String password= txt10.getText();
        String email= txt11.getText();
        if(name.equals("")){
                JOptionPane.showMessageDialog(this, "User Name is Mandatory..!!");
            }else if(age.equals("")){
                JOptionPane.showMessageDialog(this, "User Age is Mandatory..!!");
            }else if(country.equalsIgnoreCase("SELECT")){
                JOptionPane.showMessageDialog(this, "User Country is Mandatory..!!");
            }else if(sin.equals("")){
                JOptionPane.showMessageDialog(this, "User SIN Number is Mandatory.If you don't have SIN number.Please Register for sin..!!");
            }else if(status.equalsIgnoreCase("SELECT")){
                JOptionPane.showMessageDialog(this, "User VISA Status is Mandatory..!!");
            }else if(permit.equals("")){
                JOptionPane.showMessageDialog(this, "User Permit Information is Mandatory..!!");
            }else if(phoneNumber.equals("")){
                JOptionPane.showMessageDialog(this, "User Phonenumber is Mandatory..!!");
            }else if(email.equals("")){
                JOptionPane.showMessageDialog(this, "User Email is Mandatory..!!");
            }else if(userName.equals("")){
                JOptionPane.showMessageDialog(this, "Username is Mandatory..!!");
            }else if(password.equals("")){
                JOptionPane.showMessageDialog(this, "Password is Mandatory..!!");
            }else{
            String regPhoneNumber="^(\\+\\d{1,3}( )?)?((\\(\\d{3}\\))|\\d{3})[- .]?\\d{3}[- .]?\\d{4}$"
            + "|^(\\+\\d{1,3}( )?)?(\\d{3}[ ]?){2}\\d{3}$"
            + "|^(\\+\\d{1,3}( )?)?(\\d{3}[ ]?)(\\d{2}[ ]?){2}\\d{2}$";
            
            
             String regEmail= "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@" 
                              + "[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
            
             int em=0;              
              try{
      Connection cn= db_connection.DatabaseConnector.getConnection();
 
        Statement st= cn.createStatement();
      String sql = "select * from USER";
      ResultSet ps= st.executeQuery(sql);
             while(ps.next()){
            
                String email1= ps.getString("EMAIL");
                if(email1.matches(email)){
                    em++;
                }
            
             }
         }catch(Exception e){
          JOptionPane.showMessageDialog(this,e);
      }
              
            
            int phone=0;
            String phone1=phoneNumber;
            phone1=phone1.replace("-","");
            phone1=phone1.replace("(","");
            phone1=phone1.replace(")","");
            phone1=phone1.replace(" ","");
            phone1=phone1.replace("+91","");
            phone1=phone1.replace("+1","");
            
                  try{
      Connection cn= db_connection.DatabaseConnector.getConnection();
 
        Statement st= cn.createStatement();
      String sql = "select * from USER";
      ResultSet ps= st.executeQuery(sql);
             while(ps.next()){
            
                String phoneNumber1= ps.getString("PHONENUMBER");
                String phone2=phoneNumber1;
                phone2=phone2.replace("-","");
                phone2=phone2.replace("(","");
                phone2=phone2.replace(")","");
                phone2=phone2.replace(" ","");
                phone2=phone2.replace("+91","");
                phone2=phone2.replace("+1","");
                if(phone1.matches(phone2)){
                    phone++;
                }
            
             }
         }catch(Exception e){
          JOptionPane.showMessageDialog(this,e);
      }
                  int un=0;
      try{
      Connection cn= db_connection.DatabaseConnector.getConnection();
 
        Statement st= cn.createStatement();
      String sql = "select * from USER";
      ResultSet ps= st.executeQuery(sql);
             while(ps.next()){
                 String un1= ps.getString("USERNAME");
                  if(userName.equalsIgnoreCase(un1)){
                       un++;
                  }
                }
                }catch(Exception e){
          JOptionPane.showMessageDialog(this,e);
      }
                  
      
                int s=0;              
              try{
      Connection cn= db_connection.DatabaseConnector.getConnection();
 
        Statement st= cn.createStatement();
      String sql = "select * from SIN";
      ResultSet ps= st.executeQuery(sql);
             while(ps.next()){
                if(sin.matches(ps.getString("SIN")) && ps.getString("STATUS").equalsIgnoreCase("APPROVED")){
                    s++;
                }
            
             }
         }catch(Exception e){
          JOptionPane.showMessageDialog(this,e);
      }
      
      
      
                  char p = phoneNumber.charAt(0);
                   if (!name.matches("^[a-zA-z ]*$")){
                 JOptionPane.showMessageDialog(this, "Please Enter a Valid User Name");
                }else if(age.matches("[a-zA-Z]+") || !age.matches("[0-9]+") || Integer.parseInt(age)<0 || Integer.parseInt(age)>100 ){
                    JOptionPane.showMessageDialog(this, "Please Enter a Valid User Age");
                }else if(sin.matches("[a-zA-Z]+") || !sin.matches("[0-9]+")){
                    JOptionPane.showMessageDialog(this, "Please Enter a Valid SIN Number");
                }else if(sin.length()>9 || sin.length()<9){
                    JOptionPane.showMessageDialog(this, "Please Enter a Valid SIN Number");
                }else if(s<=0){
                    JOptionPane.showMessageDialog(this, "Please enter a Registered SIN Number. If you don't have sin number please Apply for new SIN Number");
                }else if(permit.matches("^[a-zA-Z]+") || !permit.matches("[0-9]+")){
                    JOptionPane.showMessageDialog(this, "Please Enter a Valid Permit Number");
                }else if(permit.length()>10 || permit.length()<10){
                    JOptionPane.showMessageDialog(this, "Please Enter a Valid Permit Number");
                }else if(!phoneNumber.matches(regPhoneNumber)){
                    JOptionPane.showMessageDialog(this, "Please Enter a Valid Phone Number");
                }else if(p == ' '){
                    JOptionPane.showMessageDialog(this, "Please Enter a Valid Phone Number");
                }else if(phoneNumber.length()>10 || phoneNumber.length()<10){
                    JOptionPane.showMessageDialog(this, "Please Enter a Valid Phone Number");
                }else if(phone>0){
                     JOptionPane.showMessageDialog(this, "Phone Number Already exists. Please provide different Phone Number");
                }else if(!email.matches(regEmail)){
                    JOptionPane.showMessageDialog(this, "Please Enter a Valid Email Address");
                }else if(em>0){
                    JOptionPane.showMessageDialog(this, "Email Address Already exists. Please provide different Email Address");
                }else if(un>0){
                    JOptionPane.showMessageDialog(this, "Username Already exists. Please provide different Username");
                }else if(!password.matches("(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}")){
                 JOptionPane.showMessageDialog(this, "Please Enter a Valid Password."
                         + "Password should be eight digits, "
                         + "Password should have atleast one Lowercase letter,"
                         + "Password should have atleast one Uppercase letter,"
                         + "Password should have atleast one Special character,"
                         + "Password should not have white space");
                }else{
        
        try{
        Connection cn=  db_connection.DatabaseConnector.getConnection();
            String sql = "insert into user(NAME,ID,AGE,COUNTRY,SIN,STATUS,PERMIT_NUMBER,PHONENUMBER,EMAIL,USERNAME,PASSWORD) values(?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps= cn.prepareStatement(sql);
            ps.setString(1,name);
            ps.setString(2,id);
            ps.setString(3,age);
            ps.setString(4, country);
            ps.setString(5,sin);
            ps.setString(6,status);
            ps.setString(7,permit);
            ps.setString(8,phoneNumber);
            ps.setString(9,email);
            ps.setString(10,userName);
            ps.setString(11, password);
            ps.execute();
            JOptionPane.showMessageDialog(this,""+name+" Profile Created Successfully..!!");
            clear();
        }catch(Exception e){
          JOptionPane.showMessageDialog(this,e);
      }
            }
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txt1ComponentAdded
        
 


        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ComponentAdded

    private void txt1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_txt1HierarchyChanged
            
       

        // TODO add your handling code here:
    }//GEN-LAST:event_txt1HierarchyChanged

    private void txt1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt1InputMethodTextChanged
       

        // TODO add your handling code here:
    }//GEN-LAST:event_txt1InputMethodTextChanged

    private void txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyTyped
           


        // TODO add your handling code here:
    }//GEN-LAST:event_txt1KeyTyped

    private void txt1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseMoved
      


        // TODO add your handling code here:
    }//GEN-LAST:event_txt1MouseMoved

    private void radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioActionPerformed
        if(radio.isSelected()){
            txt10.setEchoChar((char)0);
        }else{
            txt10.setEchoChar('*');
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_radioActionPerformed

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        NewSinAccount directory = new NewSinAccount(rightLayout,sysAdmin);
        rightLayout.add("SinPage",directory);
        CardLayout layout = (CardLayout)rightLayout.getLayout();
        layout.next(rightLayout);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked
    public void clear(){
        txt1.setText("");
        txt2.setText("");
        txt3.setText("");
        txt5.setText("");
        txt6.setSelectedIndex(0);
        txt7.setText("");
        txt9.setText("");
        txt10.setText("");
        txt4.setSelectedIndex(0);
        txt11.setText("");
        txt8.setText("");
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton radio;
    private javax.swing.JTextField txt1;
    private javax.swing.JPasswordField txt10;
    private javax.swing.JTextField txt11;
    private javax.swing.JLabel txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JComboBox<String> txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JComboBox<String> txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    // End of variables declaration//GEN-END:variables
}
