/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user;

import attributes.UserDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dheer
 */
public class NewBankAccount extends javax.swing.JPanel {

    /**
     * Creates new form NewBankAccount
     */
 JPanel innerLayout;
    UserDirectory userDirectory;
    String id;
    public NewBankAccount(JPanel innerLayout, UserDirectory userDirectory, String id) {
        this.innerLayout= innerLayout;
        this.userDirectory=userDirectory;
        this.id=id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel3.setText("BANK");
        add(jLabel3);
        jLabel3.setBounds(364, 74, 150, 40);

        jLabel2.setText(":");
        add(jLabel2);
        jLabel2.setBounds(520, 74, 4, 40);

        txt1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "CIBC", "RBC", "TD", "SCOTIA" }));
        txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt1MouseClicked(evt);
            }
        });
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        add(txt1);
        txt1.setBounds(528, 73, 200, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SAVE YOUR MONEY USING A BANK ACCOUNT");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1020, 55);

        jLabel6.setText("ACCOUNT TYPE");
        add(jLabel6);
        jLabel6.setBounds(364, 120, 150, 40);

        jLabel7.setText(":");
        add(jLabel7);
        jLabel7.setBounds(520, 121, 4, 40);

        txt2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "SAVINGS", "CHEQUING" }));
        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });
        add(txt2);
        txt2.setBounds(528, 120, 200, 40);

        jLabel8.setText("SIN NUMBER");
        add(jLabel8);
        jLabel8.setBounds(370, 220, 150, 40);

        jLabel9.setText(":");
        add(jLabel9);
        jLabel9.setBounds(520, 220, 4, 40);
        add(txt4);
        txt4.setBounds(530, 220, 200, 40);

        jLabel10.setText(":");
        add(jLabel10);
        jLabel10.setBounds(520, 270, 4, 40);
        add(txt5);
        txt5.setBounds(530, 270, 200, 40);

        jLabel11.setText("PHONE NUMBER");
        add(jLabel11);
        jLabel11.setBounds(370, 270, 150, 40);

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("CREATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(530, 320, 93, 41);

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(630, 320, 93, 41);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(370, 320, 93, 41);

        jLabel12.setText("BANK ID");
        add(jLabel12);
        jLabel12.setBounds(370, 170, 150, 40);

        jLabel13.setText(":");
        add(jLabel13);
        jLabel13.setBounds(520, 170, 4, 40);
        add(txt3);
        txt3.setBounds(530, 170, 200, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String bank= String.valueOf(txt1.getSelectedItem());
        String type= String.valueOf(txt2.getSelectedItem());
        String id1= txt3.getText();
        String sin= txt4.getText();
         String phoneNumber= txt5.getText();
        String account="";
         int min = 1;
        int max = 1000000000;
        int b = (int)(Math.random()*(max-min+1)+min);
       
        for(int i=0; String.valueOf(b).length()<8;i++){
            b = (int)(Math.random()*(max-min+1)+min);
        }
        if(String.valueOf(b).length()>8){
            account=String.valueOf(b);
            
        }

        String amount= "1000";
 
        
         if(bank.equalsIgnoreCase("SELECT")){
                JOptionPane.showMessageDialog(this, "Bank Name is Mandatory..!!");
            }else if(type.equals("SELECT")){
                JOptionPane.showMessageDialog(this, "Bank Type is Mandatory..!!");
            }else if(sin.equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(this, "amount is Mandatory..!!");
            }else if(phoneNumber.equals("")){
                JOptionPane.showMessageDialog(this, "tax is Mandatory..!!");
            }else{ 
        
                String regPhoneNumber="^(\\+\\d{1,3}( )?)?((\\(\\d{3}\\))|\\d{3})[- .]?\\d{3}[- .]?\\d{4}$"
            + "|^(\\+\\d{1,3}( )?)?(\\d{3}[ ]?){2}\\d{3}$"
            + "|^(\\+\\d{1,3}( )?)?(\\d{3}[ ]?)(\\d{2}[ ]?){2}\\d{2}$";
            int phone=0;
            String phone1=phoneNumber;
            phone1=phone1.replace("-","");
            phone1=phone1.replace("(","");
            phone1=phone1.replace(")","");
            phone1=phone1.replace(" ","");
            phone1=phone1.replace("+91","");
            phone1=phone1.replace("+1","");
            
                  try{
      Connection cn= db_connection.DatabaseConnector.getConnection();
 
        Statement st= cn.createStatement();
      String sql = "select * from USER";
      ResultSet ps= st.executeQuery(sql);
             while(ps.next()){
            
                String phoneNumber1= ps.getString("PHONENUMBER");
                String phone2=phoneNumber1;
                phone2=phone2.replace("-","");
                phone2=phone2.replace("(","");
                phone2=phone2.replace(")","");
                phone2=phone2.replace(" ","");
                phone2=phone2.replace("+91","");
                phone2=phone2.replace("+1","");
                if(phone1.matches(phone2)){
                    phone++;
                }
            
             }
         }catch(Exception e){
          JOptionPane.showMessageDialog(this,e);
      }    
                  
                  String s="";
                  String x="";
        try{
      Connection cn= db_connection.DatabaseConnector.getConnection();
      
     Statement st= cn.createStatement();
      String sql = "select * from user";
      ResultSet ps= st.executeQuery(sql);
       while(ps.next()){
        if(String.valueOf(ps.getString("ID")).matches(id))  {
            s=ps.getString("SIN");
            x=ps.getString("PHONENUMBER");
        } 
       }  
       }catch(Exception e){
          JOptionPane.showMessageDialog(this,e);
      }
                  
                  char p = phoneNumber.charAt(0);
              if(sin.matches("[a-zA-Z]+") || !sin.matches("[0-9]+")){
                    JOptionPane.showMessageDialog(this, "Please Enter a Valid SIN Number");
                }else if(!sin.matches(s)){
                    JOptionPane.showMessageDialog(this, "Please Enter a Valid SIN Number");
                }else if(!phoneNumber.matches(regPhoneNumber)){
                    JOptionPane.showMessageDialog(this, "Please Enter a Valid Phone Number");
                }else if(p == ' '){
                    JOptionPane.showMessageDialog(this, "Please Enter a Valid Phone Number");
                }else if(phoneNumber.length()>10 || phoneNumber.length()<10){
                    JOptionPane.showMessageDialog(this, "Please Enter a Valid Phone Number");
                }else if(!phoneNumber.equalsIgnoreCase(x)){
                    JOptionPane.showMessageDialog(this, "Please Enter a Valid Phone Number");
                }else{ 
                
         try{
        Connection cn=  db_connection.DatabaseConnector.getConnection();
            String sql = "INSERT INTO BANK(USERID,BANK_ID,BANK_NAME,TYPE,ACCOUNT_NUMBER,SIN,PHONE,AMOUNT,STATUS) values(?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps= cn.prepareStatement(sql);
            ps.setString(1,id);
            ps.setString(2,id1);
            ps.setString(3,bank);
            ps.setString(4,type);
            ps.setString(5,account);
            ps.setString(6, sin);
            ps.setString(7,phoneNumber);
            ps.setString(8,amount);
            ps.setString(9,"IN_PROGRESS");
            ps.execute();
            JOptionPane.showMessageDialog(this,""+bank+" Profile Created Successfully..!!");
            clear();
        }catch(Exception e){
          JOptionPane.showMessageDialog(this,e);
      }}}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    public void clear(){
        txt1.setSelectedIndex(0);
        txt2.setSelectedIndex(0);
        txt3.setText("");
        txt4.setText("");
        txt5.setText("");
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           innerLayout.remove(this);    
        Component [] componentArray = innerLayout.getComponents();
        Component c = componentArray[componentArray.length-1];
       BankAccount na= (BankAccount) c;
       na.bank();
 
        CardLayout layout = (CardLayout) innerLayout.getLayout();
        layout.previous(innerLayout);

            
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseClicked
      
       

        // TODO add your handling code here:
    }//GEN-LAST:event_txt1MouseClicked

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
         int z=0;
        String userId1 =null;

        try{
      Connection cn= db_connection.DatabaseConnector.getConnection();

     Statement st= cn.createStatement();
      String sql = "select * from BANK";
      ResultSet ps= st.executeQuery(sql);
       while(ps.next()){
           if(id.matches(ps.getString("USERID"))){
                  if(String.valueOf(ps.getString("BANK_ID")).isEmpty()){
                       txt3.setText("U00"+id+"B0"+"1"); 
                  }else{
                  userId1=String.valueOf(ps.getString("BANK_ID").substring(6));
                   z= Integer.parseInt(userId1);
                }}}
         
              txt3.setText("U00"+id+"B0"+String.valueOf(++z));

        }catch(Exception e){
          JOptionPane.showMessageDialog(this,e);
      }



        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
         int count=0;
        try{
      Connection cn= db_connection.DatabaseConnector.getConnection();
      
     Statement st= cn.createStatement();
      String sql = "select * from BANK";
      ResultSet ps= st.executeQuery(sql);
       while(ps.next()){
        if(String.valueOf(ps.getString("USERID")).matches(id))  {
            if(String.valueOf(ps.getString("BANK_NAME")).equalsIgnoreCase(String.valueOf(txt1.getSelectedItem()))){
                if(!(ps.getString("STATUS").matches("REJECTED")))
            count++;
        }
        } 
       }  
       }catch(Exception e){
          JOptionPane.showMessageDialog(this,e);
      }

        if(count>0){
           
              JOptionPane.showMessageDialog(this,"You Already have Bank Account in the Selected Bank");
               clear();

        }


        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> txt1;
    private javax.swing.JComboBox<String> txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    // End of variables declaration//GEN-END:variables
}
