/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sinUnit;


import java.awt.CardLayout;
import java.awt.Component;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.*;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;


/**
 *
 * @author dheer
 */
public class SinEmployeePage extends javax.swing.JPanel {

    /**
     * Creates new form SinEmployeePage
     */
    JPanel rightLayout;
    String id;
    String from;
    String to;
    String host;
    String sub;
    String content;
    public SinEmployeePage(JPanel rightLayout,String id) {
        this.rightLayout=rightLayout;
        this.id=id;
        initComponents();
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NAME", "SIN", "PHONENUMBER", "EMAIL", "STATUS", "REFERRED"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 50, 1920, 190);

        jButton3.setBackground(new java.awt.Color(255, 0, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("LOGOUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(1810, 0, 96, 40);

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setText("APPROVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(0, 250, 120, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/7SAPMAWIYFHHVAO3LBPXCPXRXQ.png"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(0, 0, 1980, 1080);
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked
     public void table(){
        DefaultTableModel tbl = (DefaultTableModel)table.getModel();
        tbl.setRowCount(0);
              try{
      Connection cn= db_connection.DatabaseConnector.getConnection();
      
       
     
        Statement st= cn.createStatement();
      String sql = "select * from SIN_OFFICER";
      ResultSet ps= st.executeQuery(sql);
      

      
          while(ps.next()){
           
           Object[] row = new Object[20];
          row[0]=ps.getString("NAME");
          row[1]=ps.getString("SIN");
          row[2]=ps.getString("PHONENUMBER");
          row[3]=ps.getString("EMAIL");
          row[4]=ps.getString("STATUS");
          row[5]=ps.getString("REFERRED");
          tbl.addRow(row);
         
          }
       }catch(Exception e){
          JOptionPane.showMessageDialog(this,e);
      }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    rightLayout.remove(this);
        Component [] componentArray = rightLayout.getComponents();
        Component c = componentArray[componentArray.length-1];
        CardLayout layout = (CardLayout) rightLayout.getLayout();
        layout.previous(rightLayout);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selected =table.getSelectedRow();
        int count=0;
        if(selected<0){
            JOptionPane.showMessageDialog(this, "No Row has been selected");
            return;
        }
        DefaultTableModel tbl= (DefaultTableModel)table.getModel();
         String name="";
        String sin="";
        String phoneNumber="";
        String email="";
        String status="";
        String ref="";
        String sin1= tbl.getValueAt(selected, 1).toString();
        try{
            String s1="";
            Connection cn= db_connection.DatabaseConnector.getConnection();

            Statement st= cn.createStatement();
            String sql = "select * from SIN_EMP";
            ResultSet ps= st.executeQuery(sql);

            while(ps.next()){
                if(ps.getString("SIN").equalsIgnoreCase(sin1)){
                    name= ps.getString("NAME");
                    sin=ps.getString("SIN");
                    phoneNumber=ps.getString("PHONENUMBER");
                    email=ps.getString("EMAIL");
                    status="APPROVED";
                    ref= ps.getString("REFERRED");
                   
                }
            }
            Statement st2= cn.createStatement();
            String sql2 = "select * from SIN_EMP";
            ResultSet ps2= st.executeQuery(sql2);
            while(ps2.next()){
                if(ps2.getString("SIN").equalsIgnoreCase(sin1)){
                    s1=ps2.getString("STATUS");
                }
            }


            if(!(s1.equalsIgnoreCase("APPROVED"))){

              

                String sql1= "UPDATE SIN SET STATUS='APPROVED' WHERE SIN='"+sin1+"'";
                PreparedStatement ps5= cn.prepareStatement(sql1);
                ps5.execute();

                String sql4= "UPDATE SIN_OFFICER SET STATUS='APPROVED' WHERE SIN='"+sin1+"'";
                PreparedStatement ps4= cn.prepareStatement(sql4);
                ps4.execute();

                String sql3= "UPDATE SIN_EMP SET STATUS='APPROVED' WHERE SIN='"+sin1+"'";
                PreparedStatement ps12= cn.prepareStatement(sql3);
                ps12.execute();

                String name1="";
                String email1="";
                try{
                    Connection cn1= db_connection.DatabaseConnector.getConnection();


                    Statement st5= cn1.createStatement();
                    String sql5 = "SELECT * FROM SIN_EMP";
                    ResultSet ps15= st5.executeQuery(sql5);

                    while(ps15.next()){

                            if(ps15.getString("SIN").equalsIgnoreCase(sin1)){
                                name1= ps15.getString("NAME");
                                email1=  ps15.getString("EMAIL");

                            }}

                        }catch(Exception e){
                            JOptionPane.showMessageDialog(this,e);
                        }

                        from ="dheerajjayanth@gmail.com";
                        to=email1;
                        host="localhost";
                        sub="Your "+sin1+" has Accepted";
                        content= "Hi "+name1+",\n"
                        + "\n"
                        + "We have Accepted your "+sin1+" application. You are able to use your SIN for any registration purpose. If you have any queries please contact the SIN office for more information.\n"
                        + "\n"
                        + "Thanks and Regards,\n"
                        + "SIN_EMPLOYER\n"
                        + ""+id+"\n"
                        + "\n"
                        + "If you have any concerns. Please contact us by +1 4375184224 or dheerajjayanth@gmail.com";
                        Properties p= new Properties();
                        p.put("mail.smtp.auth", "true");
                        p.put("mail.smtp.starttls.enable", "true");
                        p.put("mail.smtp.ssl.trust", "smtp.gmail.com");
                        p.put("mail.smtp.host", "smtp.gmail.com");
                        p.put("mail.smtp.port", "587");

                        Session s= Session.getDefaultInstance(p, new javax.mail.Authenticator(){
                            protected PasswordAuthentication getPasswordAuthentication(){
                                return new PasswordAuthentication("dheerajjayanth@gmail.com","rtowuvazupeivdmr");
                            }
                        });
                        try{
                            MimeMessage m = new MimeMessage(s);
                            m.setFrom(from);
                            m.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
                            m.setSubject(sub);
                            m.setText(content);
                            Transport.send(m);
                        }catch(Exception e){
                            e.printStackTrace();
                        }

                        JOptionPane.showMessageDialog(this,""+sin1+" has Successfully Approved..!!");
                        table();
                    }else{
                        JOptionPane.showMessageDialog(this,""+sin1+" has Already Approved");

                    }

                }catch(Exception e){
                    JOptionPane.showMessageDialog(this,e);
                }

                // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
