/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sysAdmin;

import attributes.SystemAdmin;
import attributes.UserDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author dheer
 */
public class AdminPage extends javax.swing.JPanel {

    /**
     * Creates new form AdminPage
     */
    JPanel rightLayout;
    UserDirectory userDirectory;
    SystemAdmin sysAdmin;
    public AdminPage(){
        initComponents();
    }
    public AdminPage(JPanel rightLayout,SystemAdmin sysAdmin) {
        this.rightLayout=rightLayout;
        this.sysAdmin=sysAdmin;
     
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        split = new javax.swing.JSplitPane();
        JPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        bn2 = new javax.swing.JButton();
        bn1 = new javax.swing.JButton();
        bn3 = new javax.swing.JButton();
        bn4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        sysLayout = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        split.setDividerLocation(200);

        JPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        bn2.setBackground(new java.awt.Color(255, 255, 255));
        bn2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bn2.setText("SIN ADMIN");
        bn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn2ActionPerformed(evt);
            }
        });

        bn1.setBackground(new java.awt.Color(255, 255, 255));
        bn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bn1.setText("BANK ADMIN");
        bn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn1ActionPerformed(evt);
            }
        });

        bn3.setBackground(new java.awt.Color(255, 255, 255));
        bn3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bn3.setText("TAX ADMIN");
        bn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn3ActionPerformed(evt);
            }
        });

        bn4.setBackground(new java.awt.Color(255, 255, 255));
        bn4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bn4.setText("INCIDENT ADMIN");
        bn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bn4, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
            .addComponent(bn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(bn1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bn2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bn3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bn4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(741, Short.MAX_VALUE))
        );

        split.setLeftComponent(JPanel1);

        sysLayout.setPreferredSize(new java.awt.Dimension(1980, 1080));
        sysLayout.setLayout(new java.awt.CardLayout());

        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperflare.com_wallpaper.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1980, 1080);

        sysLayout.add(jPanel2, "card2");

        split.setRightComponent(sysLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(split)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(split)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       reset();
                SystemAdminPage directory1 = new SystemAdminPage(rightLayout,sysLayout,sysAdmin);
                sysLayout.add("SystemAdminPage",directory1);
                CardLayout layout1 = (CardLayout)sysLayout.getLayout();
                layout1.next(sysLayout);
        rightLayout.remove(this);
        Component [] componentArray = rightLayout.getComponents();
        Component c = componentArray[componentArray.length-1];
        CardLayout layout = (CardLayout) rightLayout.getLayout();
        layout.previous(rightLayout);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn2ActionPerformed
        SinAdminLogin directory = new SinAdminLogin(sysLayout,sysAdmin);
                sysLayout.add("SinAdminLogin",directory);
                CardLayout layout = (CardLayout)sysLayout.getLayout();
                layout.next(sysLayout);
                bn1.setEnabled(false);
                bn3.setEnabled(false);
                bn4.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_bn2ActionPerformed

    private void bn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn1ActionPerformed
            BankAdminLogin directory = new BankAdminLogin(sysLayout,sysAdmin);
               sysLayout.add("BankAdminLogin",directory);
               CardLayout layout = (CardLayout)sysLayout.getLayout();
                layout.next(sysLayout);

                bn2.setEnabled(false);
                bn3.setEnabled(false);
                bn4.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_bn1ActionPerformed

    private void bn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn4ActionPerformed
         IncidentAdminLogin directory = new IncidentAdminLogin(sysLayout,sysAdmin);
                sysLayout.add("IncidentAdmin",directory);
                CardLayout layout = (CardLayout)sysLayout.getLayout();
                layout.next(sysLayout);
                bn1.setEnabled(false);
                bn2.setEnabled(false);
                bn3.setEnabled(false);
 

        // TODO add your handling code here:
    }//GEN-LAST:event_bn4ActionPerformed

    private void bn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn3ActionPerformed
         TaxAdminLogin directory = new TaxAdminLogin(rightLayout,sysLayout,sysAdmin);
                sysLayout.add("TaxAdminLogin",directory);
                CardLayout layout = (CardLayout)sysLayout.getLayout();
                layout.next(sysLayout);
                bn1.setEnabled(false);
                bn2.setEnabled(false);
                bn4.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_bn3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                
        reset();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    public void reset(){
                SystemAdminPage directory = new SystemAdminPage(rightLayout,sysLayout,sysAdmin);
                sysLayout.add("SystemAdminPage",directory);
                CardLayout layout = (CardLayout)sysLayout.getLayout();
                layout.next(sysLayout);
                bn1.setEnabled(true);
                bn2.setEnabled(true);
                bn3.setEnabled(true);
                bn4.setEnabled(true);
    }
    
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel1;
    private javax.swing.JButton bn1;
    private javax.swing.JButton bn2;
    private javax.swing.JButton bn3;
    private javax.swing.JButton bn4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane split;
    private javax.swing.JPanel sysLayout;
    // End of variables declaration//GEN-END:variables
}
